### ISSUE TITLE
There must be some hack with Nami

### ISSUE THREAD

**Issue by morfeli** [input-output-hk/nami#361]
Not able to restore wallet with written down seed phrase. I am ensured that I wrote down the exact words from my seed phrase. Is anyone else having this issue? All seed phrases are correct and the next button is disabled.

**Comment by RudahXimenes** [comment]
You probably misspelled some word. It's important to write the words correctly and in the same order you receive. If you change the order, you won't be able to open your wallet.

**Comment by HeptaSean** [comment]
If the problem still persists, I have just finished a script that might help:
https://github.com/HeptaSean/PySeedRecover

Do you have the `stake1...` address of the wallet you are trying to open? Or at least the `addr1...` receive address (with the receive address, you can easily find the stake address on cardanoscan.io)?

Since it sounds like you either got a typo in one of the words or the order wrong, it would be:
```
seedrecover -s 1 -o -a stake1... -- word1 … wordN
```
This would search for small (one changed or swapped character) typos and different orders of the words.
